services:
  nginx:
    image: nginx:alpine
    container_name: nginx-siterosiane
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    
  php:
    container_name: phpfpm-siterosiane
    build:
      context: .
    volumes:
      - ./:/var/www/html
